# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Expose the application port
EXPOSE 3000

# Set environment variables
ENV APPWRITE_PROJECT_ID=67dd74f3001832f9e837 
ENV APPWRITE_ENDPOINT=https://cloud.appwrite.io/v1 
ENV APPWRITE_PROJECT_API_KEY=standard_82a2bd52e4ae086e43608af28844149a6e006a87e7828afe606effee951ef5874f1e9b6dc538d124695837334da33ae5b98a6fef96a9a37ae7b8a94670d3e4b8594db653244c9e14a8f0e3c0a4ef232a06518f26d3137d4a875805c25eebd2fbd9c5baed1cff40df9846b482c7f0a797cbe1ac3fd432f9a69f1cc605a7424424 
ENV SERVER_URL=http://main-server:8000/api
ENV CHAT_URL=http://chat-bot-server:3002/api 
ENV PORT=3000

# Start the application
CMD ["npm", "run", "start"]
