# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy the rest of the application
COPY . .

# Expose the application port
EXPOSE 3002

# Set environment variables
ENV MONGODB_URI=mongodb+srv://wpsadi:y716RFDJ6pePnxeP@lang.wjzp8.mongodb.net/ai-chat 
ENV FLASK_API_URL=http://localhost:5000/chat 

ENV CORS_ORIGIN=*

# Start the application
CMD ["npm", "run", "start"]